#!/usr/bin/env python
# coding: utf-8

# In[2]:


import random
import json


# functions

def empty(wrd):
    
    word_length=len(wrd)

    print(word_length*" "+word_length*"_")
    print(word_length*"  "+ " |")
    print(word_length*"  "+ " |")
    print(word_length*"  "+ " |")
    print(word_length*"  "+ " |")
    #print(word_length*"_ "+" |")
    
def head(wrd):
    #prints a head
    word_length=len(wrd)
    
    print(word_length*" "+word_length*"_")
    print(word_length*" "+"O"+word_length*" "+"|")
    print(word_length*"  "+ " |")
    print(word_length*"  "+ " |")
    print(word_length*"  "+ " |")
    #print(word_length*"_ "+" |")    
    
def body(wrd):
    #prints a head and a body
    word_length=len(wrd)
    
    print(word_length*" "+word_length*"_")
    print(word_length*" "+"O"+word_length*" "+"|")
    print(word_length*" "+"|"+word_length*" "+"|")
    print(word_length*"  "+ " |")
    print(word_length*"  "+ " |")
    #print(word_length*"_ "+" |")
    
def one_leg(wrd):

    #prints a head, a body and one leg
    word_length=len(wrd)

    half_of_it = len(word)*" "

    print(word_length*" "+(word_length+1)*"_")
    print(word_length*" "+"O"+word_length*" "+"|")
    print(word_length*" "+"|"+word_length*" "+"|")
    print(half_of_it[:-1]  + "/" +" "+word_length*" "+"|")
    print(word_length*"  "+ " |")
    #print(word_length*"_ "+" |")
    
    
def two_legs(wrd):
    #prints a head, a body and 2 legs
    word_length=len(wrd)

    half_of_it = len(word)*" "

    print(word_length*" "+(word_length+1)*"_")
    print(word_length*" "+"O"+word_length*" "+"|")
    print(word_length*" "+"|"+word_length*" "+"|")
    print(half_of_it[:-1] + "/" +" "+"\\"+half_of_it[:-1]+"|")
    print(word_length*"  "+ " |")
    #print(word_length*"_ "+" |")
    
def one_arm(wrd):
    #prints a head, a body, an arm and 2 legs
    word_length=len(wrd)

    half_of_it = len(word)*" " 

    print(word_length*" "+(word_length+1)*"_")
    print(word_length*" "+"O"+word_length*" "+"|")
    print(half_of_it[:-1]+"/"+ "|"+half_of_it+"|")
    print(half_of_it[:-1]  + "/" +" "+"\\"+half_of_it[:-1]+"|")
    print(word_length*"  "+ " |")
    #print(word_length*"_ "+" |")
    
def fail(wrd):

    #prinst the whole hangman the word, and tells the player that he/she has failed!!!
    word_length=len(wrd)

    half_of_it = len(word)*" "

    print(word_length*" "+(word_length+1)*"_")
    print(word_length*" "+"O"+word_length*" "+"|")
    print(half_of_it[:-1]+"/"+ "|"+"\\"+half_of_it[:-1]+"|")
    print(half_of_it[:-1]  + "/" +" "+"\\"+half_of_it[:-1]+"|")
    print(word_length*"  "+ " |")
    #print(half_of_it+str(wrd)+" |")
    


# functions end here



print("Hi. What is your name?")

name = input()

print("Well " +name+ " nice to meet you, do you wanna play a hangman game?")


answer=""


while answer != "n":




    with open("filmovi.json") as json_file:
        data=json.load(json_file)


    #word = "Mrak film"
    #word = "Dragon ball z"

    word=random.choice(data)

    broj_pokusaja = 0

    used=list()

    the_word=""
    for ltr in word:

        if ltr == " " or ltr == ":" or ltr=="'" or ltr ==",":
            the_word+=ltr
    #     elif ltr ==":":
    #         the_word+=":"
    #     elif ltr=="'":
    #         the_word+="'"

    #     elif ltr ==",":
    #         the_word+=","
        else:
            the_word+="*"
    #print(ltr)





    answer=input()
    
    try:
        if answer == "y":


            while broj_pokusaja < 7:


                try:
                    if the_word == word:


                        print(word)
                        print("You have won motherfucker!")
                        print("")
                        print("Wanna play again?")
                        break
                        
                        
                except:
                    pass

                print("You have "+ str(6-broj_pokusaja) +" tries left")
                if broj_pokusaja == 0:
                    empty(word)
                    print("")
                    print(the_word)

                letter= input()

                while len(letter)>1:
                    print("Only one letter, please")
                    letter=input()
                    if len(letter)==1:
                        break
                
                print("You have chosen "+letter)
                print("")
                print("")
                
                used.append(letter.upper())

                if letter.lower() not in word.lower():
                    broj_pokusaja = broj_pokusaja + 1

                    print("There is no " + letter + " in the name of this movie")
                    print(" ")

                else:
                    the_word=list(the_word)
                    for num in enumerate(word):
                        #print(num)
                        #print(the_word[num[0]])
                        if letter.lower() in num or letter.upper() in num:
                            the_word[num[0]]=num[1]
                            #print(the_word[num[0]])
                            pass
                        else:
                            #the_word=the_word.replace(the_word[num[0]],num[1])
                            #print(letter)
                            pass
                    the_word="".join(the_word)


                if broj_pokusaja == 1:

                    head(word)
                    print("")
                    print(the_word)
                    print("")
                    #print("You have used "+ ",".join(used))
                    #print(" ")
                elif broj_pokusaja == 2:
                    body(word)
                    print("")
                    print(the_word)
                    print("")
                    #print("You have used "+ ",".join(used))
                    #print(" ")
                elif broj_pokusaja == 3:
                    one_leg(word)
                    print("")
                    print(the_word)
                    print("")
                    #print("You have used "+ ",".join(used))
                    #print("")
                elif broj_pokusaja == 4:
                    two_legs(word)
                    print("")
                    print(the_word)
                    print("")
                    #print("You have used "+ ",".join(used))
                    #print("")
                elif broj_pokusaja == 5:
                    one_arm(word)
                    print("")
                    print(the_word)
                    print("")
                    #print("You have used "+ ",".join(used))
                    #print(" ")
                elif broj_pokusaja == 6:
                    fail(word)

                    print("")
                    print("YOU HAVE FAILED!!!!")
                    print("The name of the movie is "+word)
                    print("")
                    print("You suck!!!")
                    print("")
                    print("Wanna play again?")
                    break
                    
                print("")
                print("You have used "+ ",".join(used))
                
        elif answer =="n":
            print("Well maybe next time :)")
            print("")
            print("Have a nice day.")
            break 
        else:
            print("well that is not an acceptable value")
            print("")
            print("Type in y for Yes or n for No")
    except ValueError:
        print('Sorry, that is not an acceptable value, try again.')
        print("")
        print("Type in y for Yes or n for No")

